version: '3'

services:

  jacow_db:
    image: postgres:12.0
    container_name: jacow-db
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'

    volumes:
      - jacow-db-vol:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    image: app
    container_name: app
    environment:
      JACOW_REFERENCES_PATH: /home/jacow/spms
      SPMS_DEBUG: 'False'
      DEV_DEBUG: 'False'
      API_DB_HOST: jacow_db
      API_DB_PORT: 5432
      API_DB_USER: '${POSTGRES_USER}'
      API_DB_PASS: '${POSTGRES_PASSWORD}'
      API_DB_NAME: '${POSTGRES_DB}'

    depends_on:
      - jacow_db
    ports:
      - "80:5000"

volumes:
  jacow-db-vol:

