"""add user

Revision ID: f11722ad55fb
Revises: 905ffdcff75d
Create Date: 2021-06-08 09:10:52.399637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11722ad55fb'
down_revision = '905ffdcff75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.add_column('log', sa.Column('conference_id', sa.Integer(), nullable=True))
    op.add_column('log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'log', 'conference', ['conference_id'], ['id'])
    op.create_foreign_key(None, 'log', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_column('log', 'user_id')
    op.drop_column('log', 'conference_id')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('conference')
    # ### end Alembic commands ###